<a href="https://colab.research.google.com/github/yaarikk21/DA-course/blob/main/hw_3_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df = pd.read_csv('drive/MyDrive/data/supermarket_sales.csv')

In [12]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [11]:
branch_profit = df.groupby('Branch')['gross income'].sum()

most_profitable_branch = branch_profit.idxmax()
highest_profit = branch_profit.max()

print(most_profitable_branch)
print(highest_profit)

C
5265.1765

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [15]:
branch_data = df[df['Branch'] == most_profitable_branch]
most_profitable_city = branch_data['City'].unique()[0]

most_profitable_city

'Naypyitaw'

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [23]:
invoices_by_category = df.pivot_table(index = 'Branch', columns = 'Product line', values = 'Invoice ID', aggfunc='count', fill_value=0)
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [25]:
most_electronics = invoices_by_category['Electronic accessories'].idxmax()
max_invoices = invoices_by_category['Electronic accessories'].max()

print(most_electronics)
print(max_invoices)

A
60

4-6. **Творче завдання на розвиток аналітичного мислення**

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.   
   
 Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

# **Питання**
1. Який день тижня є найпопулярнішим для покупок? Як це розподіляється між різними філіалами?
2. Чи є відмінності в середній сумі покупки залежно від способу оплати (готівка, кредитна карта, електронний гаманець)?
3. Як середня оцінка (Rating) варіюється залежно від категорії товарів та філіалу?

# **Відповіді**
1. Якщо певні дні є більш популярними для покупок, компанія може ввести спеціальні акції або додаткові знижки в інші, менш активні дні, щоб збільшити потік клієнтів і рівномірно розподілити навантаження на магазини.
2. Якщо певні способи оплати пов'язані із вищими сумами покупок, компанія може запропонувати додаткові стимули для клієнтів, які використовують ці способи, наприклад, бонусна картка, якою можна оплачувати як електроним гаманцем (така історія є в АТБ).
3. Виявлення товарних категорій або філіалів із низькими рейтингами дозволить бізнесу покращити обслуговування, асортимент або якість продукції.

In [34]:
df['Date'] = pd.to_datetime(df['Date'])
df['Day of Week'] = df['Date'].dt.day_name()

purchases_by_day = df.groupby(['Branch', 'Day of Week'])['Invoice ID'].count()

purchases_by_day

Branch  Day of Week
A       Friday         50
        Monday         48
        Saturday       50
        Sunday         52
        Thursday       46
        Tuesday        51
        Wednesday      43
B       Friday         51
        Monday         39
        Saturday       60
        Sunday         35
        Thursday       44
        Tuesday        53
        Wednesday      50
C       Friday         38
        Monday         38
        Saturday       54
        Sunday         46
        Thursday       48
        Tuesday        54
        Wednesday      50
Name: Invoice ID, dtype: int64

In [35]:
avg_total_by_payment = df.groupby('Payment')['Total'].mean()

avg_total_by_payment

Payment
Cash           326.181890
Credit card    324.009878
Ewallet        318.820600
Name: Total, dtype: float64

In [36]:
avg_rating_by_category_branch = df.groupby(['Branch', 'Product line'])['Rating'].mean()

avg_rating_by_category_branch

Branch  Product line
A       Electronic accessories    6.911667
        Fashion accessories       6.878431
        Food and beverages        7.253448
        Health and beauty         6.900000
        Home and lifestyle        6.930769
        Sports and travel         7.257627
B       Electronic accessories    7.116364
        Fashion accessories       6.722581
        Food and beverages        6.994000
        Health and beauty         7.100000
        Home and lifestyle        6.516000
        Sports and travel         6.509677
C       Electronic accessories    6.747273
        Fashion accessories       7.440000
        Food and beverages        7.080303
        Health and beauty         6.998077
        Home and lifestyle        7.060000
        Sports and travel         7.028889
Name: Rating, dtype: float64